import Link from "next/link";

type Company = Record<string, unknown>;
const value = (company: Company | undefined, key: string) => company?.[key] == null ? "" : String(company[key]);
const iso = (company: Company | undefined, key: string) => company?.[key] ? new Date(String(company[key])).toISOString().slice(0, 10) : "";

export function CompanyForm({ action, company }: { action: (form: FormData) => void | Promise<void>; company?: Company }) {
  return <form action={action} className="form-card">
    <div><p className="eyebrow">Cadastro empresarial</p><h1 style={{ fontSize: 30 }}>{company ? "Editar empresa" : "Nova empresa"}</h1><p className="subtitle">Campos marcados com * são obrigatórios.</p></div>
    <section className="form-section"><h2 className="section-title">Identificação</h2><div className="form-grid">
      <div className="field span-8"><label>Razão Social *</label><input name="razaoSocial" required defaultValue={value(company, "razaoSocial")} /></div><div className="field"><label>Nome Fantasia *</label><input name="nomeFantasia" required defaultValue={value(company, "nomeFantasia")} /></div>
      <div className="field"><label>CNPJ *</label><input name="cnpj" required defaultValue={value(company, "cnpj")} /></div><div className="field"><label>Inscrição Estadual</label><input name="inscricaoEstadual" defaultValue={value(company, "inscricaoEstadual")} /></div><div className="field"><label>Inscrição Municipal</label><input name="inscricaoMunicipal" defaultValue={value(company, "inscricaoMunicipal")} /></div>
      <div className="field"><label>Tipo de cliente</label><select name="tipoCliente" defaultValue={value(company, "tipoCliente") || "PRINCIPAL"}><option value="PRINCIPAL">Principal</option><option value="SECUNDARIO">Secundário</option><option value="PROSPECT">Prospect</option><option value="INATIVO">Inativo</option></select></div><div className="field"><label>Data de entrada *</label><input type="date" name="dataEntrada" required defaultValue={iso(company, "dataEntrada")} /></div><div className="field"><label>Responsável/contabilidade anterior</label><input name="responsavelAnterior" defaultValue={value(company, "responsavelAnterior")} /></div>
    </div></section>
    <section className="form-section"><h2 className="section-title">Endereço e contato</h2><div className="form-grid">
      <div className="field span-8"><label>Endereço *</label><input name="endereco" required defaultValue={value(company, "endereco")} /></div><div className="field"><label>Número</label><input name="numero" defaultValue={value(company, "numero")} /></div><div className="field"><label>Complemento</label><input name="complemento" defaultValue={value(company, "complemento")} /></div><div className="field"><label>Bairro</label><input name="bairro" defaultValue={value(company, "bairro")} /></div><div className="field"><label>CEP</label><input name="cep" defaultValue={value(company, "cep")} /></div>
      <div className="field span-6"><label>Cidade *</label><input name="cidade" required defaultValue={value(company, "cidade")} /></div><div className="field"><label>UF *</label><input name="uf" required maxLength={2} defaultValue={value(company, "uf")} /></div><div className="field"><label>Ponto de referência</label><input name="pontoReferencia" defaultValue={value(company, "pontoReferencia")} /></div>
      <div className="field span-6"><label>E-mail</label><input type="email" name="email" defaultValue={value(company, "email")} /></div><div className="field"><label>Telefone 1</label><input name="telefone1" defaultValue={value(company, "telefone1")} /></div><div className="field"><label>Telefone 2</label><input name="telefone2" defaultValue={value(company, "telefone2")} /></div>
    </div></section>
    <section className="form-section"><h2 className="section-title">Atividade e operação</h2><div className="form-grid">
      <div className="field"><label>Capital social</label><input type="number" step="0.01" name="capitalSocial" defaultValue={value(company, "capitalSocial")} /></div><div className="field span-8"><label>CNAE principal *</label><input name="cnaePrincipal" required defaultValue={value(company, "cnaePrincipal")} /></div><div className="field span-6"><label>CNAEs secundários (um por linha)</label><textarea name="cnaesSecundarios" defaultValue={Array.isArray(company?.cnaesSecundarios) ? company.cnaesSecundarios.join("\n") : ""} /></div><div className="field span-6"><label>Histórico de alterações (uma por linha)</label><textarea name="historicoAlteracoes" defaultValue={Array.isArray(company?.historicoAlteracoes) ? company.historicoAlteracoes.join("\n") : ""} /></div>
      <div className="field"><label>Ramo de atividade *</label><input name="ramoAtividade" required defaultValue={value(company, "ramoAtividade")} /></div><div className="field span-6"><label>Serviço/produto *</label><input name="servicoProduto" required defaultValue={value(company, "servicoProduto")} /></div><div className="field"><label>Quantidade de funcionários</label><input type="number" min="0" name="quantidadeFuncionarios" defaultValue={value(company, "quantidadeFuncionarios") || "0"} /></div><div className="field"><label>Tempo de empresa</label><input name="tempoEmpresa" placeholder="Ex.: 5 anos" defaultValue={value(company, "tempoEmpresa")} /></div>
    </div></section>
    <section className="form-section"><h2 className="section-title">Fiscal, financeiro e compliance</h2><div className="form-grid">
      <div className="field"><label>Situação dos alvarás</label><select name="situacaoAlvaras" defaultValue={value(company, "situacaoAlvaras") || "PENDENTE"}><option value="PRONTO">Pronto</option><option value="EM_ANDAMENTO">Em andamento</option><option value="PENDENTE">Pendente</option><option value="NAO_APLICAVEL">Não aplicável</option></select></div><div className="field"><label>Regime tributário</label><select name="regimeTributario" defaultValue={value(company, "regimeTributario") || "SIMPLES_NACIONAL"}><option value="SIMPLES_NACIONAL">Simples Nacional</option><option value="LUCRO_PRESUMIDO">Lucro Presumido</option><option value="LUCRO_REAL">Lucro Real</option><option value="MEI">MEI</option><option value="ISENTO">Isento</option></select></div><div className="field"><label>Ranking</label><select name="ranking" defaultValue={value(company, "ranking") || "C"}>{["C", "B", "A", "S", "SS"].map((r) => <option key={r}>{r}</option>)}</select></div>
      <div className="field"><label>Data da baixa</label><input type="date" name="dataBaixa" defaultValue={iso(company, "dataBaixa")} /></div><div className="field"><label>Atualização bancária</label><input type="date" name="dataAtualizacaoBancaria" defaultValue={iso(company, "dataAtualizacaoBancaria")} /></div><label className="check-field"><input type="checkbox" name="participaLicitacoes" defaultChecked={Boolean(company?.participaLicitacoes)} /> Participa de licitações</label><label className="check-field"><input type="checkbox" name="irpfSociosNaContabilidade" defaultChecked={Boolean(company?.irpfSociosNaContabilidade)} /> IRPF dos sócios conosco</label><label className="check-field"><input type="checkbox" name="pendenciasFiscais" defaultChecked={Boolean(company?.pendenciasFiscais)} /> Possui pendências fiscais</label>
    </div></section>
    <div className="form-actions"><Link className="button secondary" href="/">Cancelar</Link><button className="button" type="submit">{company ? "Salvar alterações" : "Cadastrar empresa"}</button></div>
  </form>;
}
