import { certificateStatus } from "@/lib/certificate-status";
import { currency, date, enumLabel } from "@/lib/format";

type SheetCompany = Record<string, any>;
const yesNo = (value: boolean) => `${value ? "☒ Sim   ☐ Não" : "☐ Sim   ☒ Não"}`;
const choice = (active: boolean, label: string) => `${active ? "☒" : "☐"} ${label}`;
const show = (value: unknown) => value == null || value === "" ? "—" : String(value);

function Cell({ label, children, className = "" }: { label: string; children?: React.ReactNode; className?: string }) {
  return <div className={`cell ${className}`}><span className="cell-label">{label}</span><span className="cell-value">{children || "—"}</span></div>;
}

export function CompanySheet({ company }: { company: SheetCompany }) {
  const partners = company.socios ?? [];
  const contacts = company.contatos ?? [];
  const certificates = company.certificados ?? [];
  const changes = company.alteracoes ?? [];
  return <article className="sheet" aria-label={`Ficha cadastral de ${company.razaoSocial}`}>
    <header className="sheet-header"><div className="sheet-logo"><span className="sheet-logo-mark"><i /><i /><i /></span><span><strong>AutCompany</strong><small>GESTÃO CONTÁBIL INTEGRADA</small></span></div><div className="sheet-title">FICHA CADASTRAL</div></header>
    <section className="sheet-box"><div className="bar">Qualificação da empresa</div><div className="company-row"><Cell label="Razão Social">{company.razaoSocial}</Cell><Cell label="Status">{enumLabel(company.status)}</Cell></div><div className="company-row"><Cell label="Nome Fantasia">{company.nomeFantasia}</Cell><Cell label="Ranking">{company.ranking}</Cell></div><div className="grid g-3"><Cell label="CNPJ">{company.cnpj}</Cell><Cell label="Inscrição Estadual">{company.inscricaoEstadual}</Cell><Cell label="Inscrição Municipal">{company.inscricaoMunicipal}</Cell></div><div className="company-row"><Cell label="Endereço completo">{[company.endereco, company.numero, company.complemento, company.bairro].filter(Boolean).join(", ")}</Cell><Cell label="CEP">{company.cep}</Cell></div><div className="grid g-4"><Cell label="Cidade">{company.cidade}</Cell><Cell label="UF">{company.uf}</Cell><Cell label="E-mail">{company.email}</Cell><Cell label="Telefone">{company.telefone1}</Cell></div><div className="grid g-4"><Cell label="Capital Social">{currency(company.capitalSocial)}</Cell><Cell label="CNAE principal">{company.cnaePrincipal}</Cell><Cell label="Ramo de atividade">{company.ramoAtividade}</Cell><Cell label="Regime">{enumLabel(company.regimeTributario)}</Cell></div><Cell label="CNAEs secundários" className="compact">{company.cnaesSecundarios?.join(" • ") || "—"}</Cell></section>
    <section className="sheet-box"><div className="bar">Titular e sócios</div><div className="partners-head"><div>Nome / situação</div><div>CPF / período</div><div>%</div></div>{partners.map((relation: any) => <div className="partner" key={relation.socio.id}><div><strong>{relation.socio.nome}</strong>{relation.cargo ? ` — ${relation.cargo}` : ""}<span className="partner-note">{relation.dataSaida ? "Sócio retirante" : "Sócio atual"}{relation.administrador ? " · Administrador" : ""}</span></div><div>{relation.socio.cpf}<span className="partner-note">{date(relation.dataEntrada)} → {date(relation.dataSaida)}</span></div><div>{relation.participacao == null ? "—" : `${Number(relation.participacao)}%`}</div></div>)}</section>
    <section className="sheet-box"><div className="bar">Contatos</div><div className="sheet-list">{contacts.length ? contacts.map((contact: any) => <div className="sheet-list-row" key={contact.id}><strong>{contact.nome}</strong><span>{enumLabel(contact.tipo)}{contact.ativo ? "" : " · Inativo"}</span><span>{show(contact.telefone || contact.whatsapp)}</span><span>{show(contact.email)}</span></div>) : <div className="sheet-list-row"><span>Sem contatos cadastrados.</span></div>}</div></section>
    <section className="sheet-box"><div className="bar">Certificados digitais</div><div className="sheet-list">{certificates.length ? certificates.map((certificate: any) => <div className="sheet-list-row" key={certificate.id}><strong>{certificate.titularTipo}</strong><span>Emissão: {date(certificate.dataEmissao)}</span><span>Vencimento: {date(certificate.dataVencimento)}</span><span>{enumLabel(certificateStatus(certificate.dataVencimento))}</span></div>) : <div className="sheet-list-row"><span>Sem certificados cadastrados.</span></div>}</div></section>
    <section className="sheet-box"><div className="bar">Dados adicionais e operação</div><div className="grid g-4"><Cell label="Qtd. funcionários" className="compact">{company.quantidadeFuncionarios}</Cell><Cell label="Data de entrada" className="compact">{date(company.dataEntrada)}</Cell><Cell label="Data de saída" className="compact">{date(company.dataSaidaEscritorio)}</Cell><Cell label="Responsável interno" className="compact">{company.responsavelInterno}</Cell></div><div className="inline-data"><strong>Alvarás:</strong> {enumLabel(company.situacaoAlvaras)} &nbsp; <strong>Licitações:</strong> {yesNo(company.participaLicitacoes)} &nbsp; <strong>IRPF Sócios:</strong> {yesNo(company.irpfSociosNaContabilidade)}</div><div className="inline-data"><strong>Regime:</strong> {choice(company.regimeTributario === "SIMPLES_NACIONAL", "Simples Nacional")} &nbsp; {choice(company.regimeTributario === "LUCRO_PRESUMIDO", "Lucro Presumido")} &nbsp; {choice(company.regimeTributario === "LUCRO_REAL", "Lucro Real")} &nbsp; {choice(company.regimeTributario === "MEI", "MEI")}</div><div className="inline-data"><strong>Motivo da saída:</strong> {show(company.motivoSaidaEscritorio)}</div><div className="inline-data"><strong>Observações internas:</strong> {show(company.observacoesInternas)}</div></section>
    <section className="sheet-box"><div className="bar">Histórico cadastral relevante</div><div className="sheet-history">{changes.length ? changes.map((change: any) => <div key={change.id}><strong>{date(change.data)} · {enumLabel(change.tipo)}</strong><span>{change.descricao}</span></div>) : <p>Sem alterações estruturadas registradas.</p>}</div></section>
    <footer className="workflow"><div className="bar">Tramitação de documentos internos</div><div className="workflow-grid">{["Departamento de Legalização", "Departamento Pessoal (DP)", "Departamento Fiscal"].map((department) => <div className="workflow-item" key={department}><span className="workflow-check" />{department}<div className="signature-line">______/______/________<br /><strong>DATA</strong></div></div>)}</div></footer>
  </article>;
}
