export const demoEmpresa = {
  id: "demonstracao",
  razaoSocial: "Batista Soluções Empresariais Ltda",
  nomeFantasia: "Batista Soluções",
  cnpj: "12.345.678/0001-90",
  inscricaoEstadual: "110.042.490.114",
  inscricaoMunicipal: "8.765.432-1",
  endereco: "Av. das Empresas",
  numero: "1250",
  complemento: "Sala 402",
  bairro: "Centro Empresarial",
  cidade: "São Paulo",
  uf: "SP",
  cep: "01010-001",
  pontoReferencia: "Próximo ao Fórum",
  email: "contato@batistasolucoes.com.br",
  telefone1: "(11) 3456-7890",
  telefone2: "(11) 99876-5432",
  capitalSocial: 150000,
  cnaePrincipal: "69.20-6-01 — Atividades de contabilidade",
  cnaesSecundarios: ["70.20-4-00 — Consultoria em gestão empresarial"],
  ramoAtividade: "Serviços profissionais",
  servicoProduto: "Contabilidade e consultoria",
  quantidadeFuncionarios: 18,
  tempoEmpresa: "12 anos",
  historicoAlteracoes: ["2024 — Alteração de endereço", "2022 — Aumento do capital social"],
  dataEntrada: new Date("2024-02-05T00:00:00.000Z"),
  responsavelAnterior: "Almeida Contabilidade",
  situacaoAlvaras: "PRONTO",
  participaLicitacoes: true,
  tipoCliente: "PRINCIPAL",
  regimeTributario: "LUCRO_PRESUMIDO",
  dataBaixa: null,
  irpfSociosNaContabilidade: true,
  dataAtualizacaoBancaria: new Date("2026-06-18T00:00:00.000Z"),
  pendenciasFiscais: false,
  ranking: "S",
  createdAt: new Date(),
  updatedAt: new Date(),
  socios: [
    { participacao: 60, cargo: "Sócio administrador", socio: { id: "s1", nome: "Marina Batista", cpf: "123.456.789-00", endereco: "São Paulo/SP", vinculos: [{ id: "v1", tipo: "SOCIO_EM_OUTRA_EMPRESA", descricao: "Sócia na empresa Batista Participações", empresaDestinoId: null }] } },
    { participacao: 40, cargo: "Sócio", socio: { id: "s2", nome: "Rafael Batista", cpf: "987.654.321-00", endereco: "São Paulo/SP", vinculos: [{ id: "v2", tipo: "VINCULO_DE_INTERESSE", descricao: "Vínculo com Batista Imóveis", empresaDestinoId: null }] } },
  ],
};
